define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Nom du groupe",
    "DescriptionFieldLabel": "Champ de description",
    "AppLocalEnvironmentSharePoint": "L'application s'exécute dans votre environnement local en tant que composant WebPart SharePoint",
    "AppLocalEnvironmentTeams": "L'application s'exécute dans votre environnement local en tant qu'application Microsoft Teams",
    "AppLocalEnvironmentOffice": "L'application s'exécute dans votre environnement local dans office.com",
    "AppLocalEnvironmentOutlook": "L'application s'exécute dans votre environnement local dans Outlook",
    "AppSharePointEnvironment": "L'application s'exécute sur une page SharePoint",
    "AppTeamsTabEnvironment": "L'application s'exécute dans Microsoft Teams",
    "AppOfficeEnvironment": "L'application s'exécute dans office.com",
    "AppOutlookEnvironment": "L'application s'exécute dans Outlook",
    "UnknownEnvironment": "L'application s'exécute dans un environnement inconnu",
    // Web Part property pane
    "WebPartTitleLabel": "Titre du composant",
    "QuickLinksLabel": "Liens rapides",
    // Property pane form labels
    "LinkTitleLabel": "Titre du lien",
    "LinkTitleDescription": "Saisissez un titre descriptif pour le lien",
    "URLLabel": "URL",
    "URLDescription": "Saisissez l'URL complète (par exemple, https://example.com) ou une URL relative",
    "IconTypeLabel": "Type d'icône",
    "FluentUIIconOption": "Icône Fluent UI",
    "FluentUIIconAriaLabel": "Utiliser une icône Fluent UI",
    "CustomImageURLOption": "URL d'image personnalisée",
    "CustomImageURLAriaLabel": "Utiliser une image personnalisée depuis une URL",
    "IconTypeDescription": "Choisissez entre une icône Fluent UI ou une image personnalisée pour ce lien",
    "ImageURLLabel": "URL de l'image",
    "IconNameLabel": "Nom de l'icône",
    "ImageURLPlaceholder": "https://example.com/logo.png",
    "IconNamePlaceholder": "Link",
    "ImageURLDescription": "Saisissez une URL complète vers une image (par exemple, https://example.com/logo.png)",
    "IconNameDescription": "Saisissez un nom d'icône Fluent UI (par exemple, Home, Globe, Mail, Document)",
    "OpenInNewTabLabel": "Ouvrir dans un nouvel onglet",
    "OpenInNewTabAriaLabel": "Ouvrir le lien dans un nouvel onglet du navigateur",
    // Property pane buttons
    "UpdateButton": "Mettre à jour",
    "UpdateButtonAriaLabel": "Mettre à jour le lien avec les nouvelles informations",
    "CancelButton": "Annuler",
    "CancelButtonAriaLabel": "Annuler la modification et ignorer les modifications",
    "AddLinkButton": "Ajouter un lien",
    "AddLinkButtonAriaLabel": "Ajouter le nouveau lien à la liste",
    "LinkActionsAriaLabel": "Actions du formulaire",
    "LinkActionsAriaLabelFormat": "Actions pour {0}",
    // Property pane links list
    "CurrentLinksLabel": "Liens actuels",
    "ConfiguredLinksAriaLabelSingular": "{0} lien rapide configuré",
    "ConfiguredLinksAriaLabelPlural": "{0} liens rapides configurés",
    "OpensInNewTab": "S'ouvre dans un nouvel onglet",
    "OpensInSameTab": "S'ouvre dans le même onglet",
    "CustomIcon": "Icône personnalisée",
    "EditLinkTitleFormat": "Modifier {0}",
    "EditLinkAriaLabelFormat": "Modifier le lien : {0}",
    "DeleteLinkTitleFormat": "Supprimer {0}",
    "DeleteLinkAriaLabelFormat": "Supprimer le lien : {0}",
    "EditFormAriaLabel": "Modifier le lien rapide",
    "AddFormAriaLabel": "Ajouter un nouveau lien rapide",
    // URL validation errors
    "URLErrorDangerousScheme": "Les URL utilisant les schémas javascript: ou data: ne sont pas autorisées",
    "URLErrorInvalidFormat": "L'URL doit commencer par http://, https://, ou être une URL relative (/, ./, ../, #, ?)",
    // Component messages
    "NoLinksMessage": "Aucun lien rapide configuré. Veuillez modifier le composant WebPart pour ajouter des liens.",
    "OpensInNewTabSuffix": "(s'ouvre dans un nouvel onglet)"
  }
});
